# read more on https://www.codingforentrepreneurs.com/shorts/how-i-use-redis-for-new-projects-with-docker-compose/
version: '3.9'
services:
    redis:
        image: redis
        restart: always
        ports:
            - 6170:6379
        volumes:
            - data:/data
        entrypoint: redis-server --appendonly yes
volumes:
    data:

networks:
  default:
    name: scrape_scheduler_network
