# read more on https://www.codingforentrepreneurs.com/shorts/how-i-use-redis-for-new-projects-with-docker-compose/
version: '3.9'
services:
    redis:
        image: redis
        restart: always
        ports:
            - 6170:6379
        volumes:
            - redis_data_a:/data
        entrypoint: redis-server --appendonly yes
volumes:
    redis_data_a:

networks:
  default:
    name: redis_network
