# Generated by Django 5.0.3 on 2024-03-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productscrapeevent",
            name="asin",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
