# Generated by Django 5.0.3 on 2024-03-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product__trigger_scrape_product_trigger_scrape_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="_trigger_scrape",
        ),
        migrations.RemoveField(
            model_name="product",
            name="trigger_scrape",
        ),
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
