# Generated by Django 5.0.3 on 2024-03-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_product__trigger_scrape_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True, help_text="Scrape daily?"),
        ),
    ]
